# Generated by Django 5.0.14 on 2026-01-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miepi', '0002_inscrito_iglesia_inscrito_pastor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=50),
        ),
    ]
